services:
  - type: web
    name: teller-phase5-codex-1
    repo: https://github.com/dvanosdol88/teller-phase5-codex
    branch: main
    buildCommand: |
      npm install
      # Build React app if present
      if [ -d "ai-studio-app" ]; then
        npm --prefix ai-studio-app ci
        npm --prefix ai-studio-app run build
      fi
    startCommand: node server.js
    plan: starter
    envVars:
      - key: BACKEND_URL
        value: https://teller-phase5-codex-1.onrender.com
      - key: FEATURE_MANUAL_DATA
        value: true
      - key: DATABASE_URL
        sync: false
      - key: MANUAL_DATA_TABLE
        value: manual_data
      - key: PGSSL
        value: "true"
      - key: MANUAL_DATA_READONLY
        value: "false"
      - key: MANUAL_DATA_DRY_RUN
        value: "false"
      - key: VITE_API_BASE_URL
        value: /api
